language: java

sudo: false

jdk:
  - openjdk13

env:
  global:
    - MAVEN_PROFILES="it"

cache:
  directories:
    - $HOME/.m2

script: "mvn clean verify -P$MAVEN_PROFILES"

install: /bin/true

notifications:
  irc:
    channels:
      - "irc.freenode.org#carcv"
    on_success: always
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
